---
info:
  component: Documentation

spring:
  profiles: default

server:
  port: 8080

documentation: 
  baseurl: http://localhost
  swagger: 
    services:   
      - 
        name: Service1
        url: http://petstore.swagger.io/v2/swagger.json
        version: 2.0