---
  documentation: 
    baseurl: http://localhost
    swagger: 
      services:   
        - 
          name: Service1
          url: http://petstore.swagger.io/v2/swagger.json
          version: 2.0
        -
          name: Service2
          url: https://raw.githubusercontent.com/swagger-api/swagger-samples/master/java/inflector-dropwizard/src/main/swagger/swagger.yaml
          version: 2.0 
